apriltag subsystem
FRC4048/FRC2023_Java pull request #11
Opened 2023-02-14 01:52 UTC by AayushK123

it is a new apriltag subsystem to get networktable entries

2023-02-23 21:30 UTC, bengold22 requested changes

2023-02-23 21:30 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/AprilTagSubsystem.java
> +    this.horizontalOffsetRightCam = tableRight.getEntry("horizontalOffset");
Why don't you have an angle for the right camera?

2023-02-23 21:30 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/AprilTagSubsystem.java
> +    return tagIdLeftCam.getInteger(0L);
This logic should be:

get ID of left cam
if not null, return left cam ID
else 
return right cam ID

2023-02-23 21:30 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/AprilTagSubsystem.java
> +    double rotation = yRotationLeftCam.getDouble(0.0) + yRotationRightCam.getDouble(0.0);
As discussed, this won't work

2023-02-24 00:38 UTC, MatthewSpofford approved these changes
Functionally it looks good to me (and all of @bengold22's comments appear to be resolved). My one nitpicky suggestion if you have extra time, is think of a way to generalize and remove the repeating if/else statements that are checking the camera IDs.

2023-02-24 01:50 UTC, bengold22 approved these changes

2023-02-24 01:51 UTC, merged