Fc arm
FRC4048/FRC2023_Java pull request #20
Opened 2023-02-22 22:59 UTC by fwc4838

Increased grip strength, Added voltage based movement to arm before PID based movement, tuned PID mostly.

2023-02-22 23:11 UTC, batchen1 commented on src/main/java/frc/robot/Constants.java
>    public static final double GRIPPER_TIMEOUT = 5.0;
I think we can reduce the timeout to maybe 2 seconds

2023-02-22 23:15 UTC, batchen1 commented on src/main/java/frc/robot/Robot.java
> +    SmartShuffleboard.put("PID", "encoder", (arm.getEncoderValue()));
this should be in the arm periodic, the value should go to the "Gripper" tab and be under if (Constants.DEBUG)

2023-02-23 00:08 UTC, batchen1 requested changes
Didn't have a chance to look at the entire PR, but you can work on these in the meantime.

2023-02-23 00:08 UTC, batchen1 commented on src/main/java/frc/robot/Robot.java
> +    m_robotContainer.getArm().getNeoMotor().getPIDController().setI(0);
Make this a method in the Arm subsystem.

2023-02-23 00:08 UTC, batchen1 commented on src/main/java/frc/robot/RobotContainer.java
>    private XboxController xbox = new XboxController(2);
seems like we have 2 xbox controllers that are using the same port. Not sure how this is even working, but we need to keep the CommandXboxController and get rid of the other one.

2023-02-23 00:08 UTC, batchen1 commented on src/main/java/frc/robot/RobotContainer.java
> +    SmartShuffleboard.putCommand("PID", "ArmMoveSequence 39", new ArmMoveSequence(arm, 39.0));
Not sure we need this anymore, and even if we do, we probably want just one command that will get an input from the shuffleboard, and also move it to the Arm periodic under if DEBUG

2023-02-23 00:08 UTC, batchen1 commented on src/main/java/frc/robot/RobotContainer.java
> +    cmdController.button(3).onTrue(new ResetExtenderEncoder(extender));
buttons should probably be constants so we don't reuse them

2023-02-23 00:08 UTC, batchen1 commented on src/main/java/frc/robot/RobotContainer.java
>      SmartShuffleboard.putCommand("Extender", "Set position=5709", new ExtendToPosition(extender, 5709));
move shuffleboard to respective subsystems and under Debug or delete

2023-02-23 00:08 UTC, batchen1 commented on src/main/java/frc/robot/commands/Stow.java
> +                new VoltageMoveArm(arm, 3.0, 0.0)
should be a constant

2023-02-23 21:06 UTC, bengold22 requested changes

2023-02-23 21:06 UTC, bengold22 commented on src/main/java/frc/robot/Constants.java
> +  //xbox buttons
There's are existing WPILIB objects that have all these constants:

XboxController.Button

for instance:
    int aValue = XboxController.Button.kA.value;

2023-02-23 21:06 UTC, bengold22 commented on src/main/java/frc/robot/Constants.java
> +  //xbox buttons
There is also XBoxController.Axis for all the axis entries

2023-02-23 21:06 UTC, bengold22 commented on src/main/java/frc/robot/RobotContainer.java
> +  //Xbox controllers
You're using two numbers here (4 and 3) which means this will be two xbox controllers. Is that the intent?

2023-02-23 21:06 UTC, bengold22 commented on src/main/java/frc/robot/RobotContainer.java
> +    xboxManual.axisGreaterThan(Constants.R_STICK_X_AXIS, 0.25).onTrue(new ManualMoveGripper (gripper, () -> 0.8 ));
We should move these numbers to Constants.

2023-02-23 21:06 UTC, bengold22 commented on src/main/java/frc/robot/commands/arm/VoltageMoveArm.java
> +        //negative value moves arm up
Nit: indentation is messy

2023-02-23 21:06 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/Arm.java
>      encoderValue = encoder.getPosition();
Why are we keeping an instance variable with the encoderValue instead of reading it from encoder.getPosition() when needed?

2023-02-23 22:12 UTC, fwc4838 commented on src/main/java/frc/robot/RobotContainer.java
> +  //Xbox controllers
yes

2023-02-24 01:32 UTC, batchen1 requested changes

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/Robot.java
> +    m_robotContainer.getArm().zeroPID();
Can we add a call to zeroPID() in autonomousInit() and testInit()?

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/RobotContainer.java
> +  private CommandXboxController xboxManual = new CommandXboxController(4);
xbox controllers are 2,3 (not 3,4)

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/commands/arm/ArmMoveSequence.java
> +public class ArmMoveSequence extends SequentialCommandGroup {
This needs to change

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/commands/arm/HoldArmPID.java
> +        SmartShuffleboard.put("Arm", "P Gain", pidController.getP());
put in if DEBUG

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/RobotContainer.java
> +    xboxManual.button(4).whileTrue(new ManualMoveArm(arm, Constants.MANUAL_ARM_SPEED));
change 4 to a constant, also - there's only a button to move the arm in one direction.

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/commands/arm/VoltageMoveArm.java
> +        return Math.abs(angle - arm.getEncoderValue()) < 2.5;
threshold should be a constant

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/subsystems/Arm.java
> +      SmartShuffleboard.put("Gripper", "arm encoder", (getEncoderValue()));
change tab from gripper to arm

2023-02-24 01:32 UTC, batchen1 commented on src/main/java/frc/robot/subsystems/Arm.java
> +    if (val > 4.5) {
4.5 should be a constant

2023-02-24 01:55 UTC, batchen1 approved these changes

2023-02-24 01:57 UTC, bengold22 approved these changes

2023-02-24 01:57 UTC, merged