Fc arm protect
FRC4048/FRC2023_Java pull request #27
Opened 2023-02-24 23:49 UTC by fwc4838

ARM PROTECTIONS! IT DOESN'T BREAK NOW

2023-02-25 18:09 UTC, bengold22 requested changes

2023-02-25 18:09 UTC, bengold22 commented on src/main/java/frc/robot/commands/extender/ManualMoveExtender.java
> +        extender.move(speed);
You flipped the sign back here, was this intentional?

2023-02-25 18:09 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/Arm.java
> +    if (val < 1 && !safeToExtend() && !extender.safeToLowerArm()) {
Shouldn't this be val < 0, not val < 1? You want to make this check only when it's going down?

2023-02-25 18:09 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/Arm.java
> +    if (val < 1 && !safeToExtend() && !extender.safeToLowerArm()) {
So as written this logic kicks in whenever the arm is relatively low, and extender is relatively extended, correct?

2023-02-26 21:47 UTC, armadilloz requested changes

2023-02-26 21:47 UTC, armadilloz commented on src/main/java/frc/robot/commands/arm/HoldArmPID.java
>      private Double angle;
Is this command going to be deleted?

2023-02-26 21:47 UTC, armadilloz commented on src/main/java/frc/robot/commands/arm/ManualMoveArm.java
> +        arm.setVoltage(power);
Is this command used?

2023-02-26 21:47 UTC, armadilloz commented on src/main/java/frc/robot/commands/arm/VoltageMoveArm.java
> +        //positive angle -> positive power
Is this command used?

2023-02-26 21:47 UTC, armadilloz commented on src/main/java/frc/robot/commands/drive/Move.java
> +        drivetrain.setPower(Constants.DRIVE_FRONT_LEFT_D, 0);
Shouldn't there be a drivetrain.stop() command?

2023-02-26 21:47 UTC, armadilloz commented on src/main/java/frc/robot/commands/extender/ExtendToPosition.java
>      @Override
Add timeout

2023-02-27 16:20 UTC, merged