Nh protection
FRC4048/FRC2023_Java pull request #33
Opened 2023-02-26 21:59 UTC by noahheller

2023-02-26 22:30 UTC, armadilloz requested changes

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +public final class Mechanism extends SubsystemBase {
Maybe rename this to MechanismProtection>

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/RobotContainer.java
> +    //DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE
??

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/RobotContainer.java
> +    manualController.button(XboxController.Button.kLeftBumper.value).onTrue(new Stow(arm,gripper,extender));
Duplicate of line 98

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/commands/arm/HoldArmPID.java
> +        arm.setPIDReference(angle);
Not sure what this does - need someone else to take a look...

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/commands/drive/Move.java
> +        return drivetrain.getRelEnc(Constants.DRIVE_BACK_LEFT_D) - startEnc >= distance/(Constants.WHEEL_RADIUS * 2 * Math.PI);
This needs a timeout

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/commands/extender/ExtendToPosition.java
>      @Override
Timeout?

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Arm.java
> +  public void setPIDReference(double reference) {
Is this better named moveTo()?

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Extender.java
> +//        if (speed < 0 || Mechanism.getInstance().safeToExtend()) {
remove comments

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +     public static Mechanism getInstance() {
I would rather have the subsystems hold all instances and call setMechanism to all that need it. No need for static instance.

2023-02-26 22:30 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +     public void periodic() {
Surround by `isDebug()`

2023-02-26 23:29 UTC, fwc4838 commented on src/main/java/frc/robot/subsystems/Arm.java
> +  public void setPIDReference(double reference) {
this is what it should be

2023-02-26 23:38 UTC, noahheller commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +public final class Mechanism extends SubsystemBase {
done

2023-02-26 23:38 UTC, noahheller commented on src/main/java/frc/robot/RobotContainer.java
> +    //DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE
done

2023-02-26 23:40 UTC, noahheller commented on src/main/java/frc/robot/RobotContainer.java
> +    manualController.button(XboxController.Button.kLeftBumper.value).onTrue(new Stow(arm,gripper,extender));
done

2023-02-26 23:42 UTC, noahheller commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +     public void periodic() {
done

2023-02-26 23:42 UTC, noahheller commented on src/main/java/frc/robot/subsystems/Extender.java
> +//        if (speed < 0 || Mechanism.getInstance().safeToExtend()) {
done

2023-02-26 23:46 UTC, noahheller commented on src/main/java/frc/robot/commands/drive/Move.java
> +        return drivetrain.getRelEnc(Constants.DRIVE_BACK_LEFT_D) - startEnc >= distance/(Constants.WHEEL_RADIUS * 2 * Math.PI);
Deleted not needed move class

2023-02-27 00:29 UTC, noahheller commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +     public static Mechanism getInstance() {
can you elaborate, I'm not sure I understand

2023-02-27 00:30 UTC, noahheller commented on src/main/java/frc/robot/commands/extender/ExtendToPosition.java
>      @Override
addressed in another branch

2023-02-27 00:36 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Extender.java
> +//        if (speed < 0 || Mechanism.getInstance().safeToExtend()) {
Not done, but no blocker either

2023-02-27 00:40 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +     public static Mechanism getInstance() {
Not an issue of correctness, but normally all subsystems are just POJOs and do not implement the singleton pattern with stating instance and getInstance method.
I'd rather this would behave like that so that it is the same as the rest of the system. RobotContainer would instantiate, and nom need for singleton methods like getInstance. Everywhere you need access to the instance you either given one through constructor, through setProtection or through Robot.getContainer.getProtection()
I'm going to approve the PR anyways since we need this code to move forward.

2023-02-27 00:41 UTC, armadilloz commented
There are conflicts. Are you going to resolve them yourself or would you like me to?

2023-02-27 02:15 UTC, noahheller commented on src/main/java/frc/robot/subsystems/Mechanism.java
> +     public static Mechanism getInstance() {
Thank you for elaborating, I updated the branch using the design pattern requested to keep things consistent.

2023-02-27 02:19 UTC, noahheller commented
> There are conflicts. Are you going to resolve them yourself or would you like me to?

Mostly imports. I believe I fixed them.

2023-02-27 14:35 UTC, armadilloz approved these changes

2023-02-27 16:20 UTC, merged