Updated Utils
FRC4048/FRC2023_Java pull request #4
Opened 2023-01-14 18:23 UTC by Sahiltheram

2023-01-15 23:01 UTC, armadilloz requested changes

2023-01-15 23:01 UTC, armadilloz commented on src/main/java/frc/robot/utils/diag/DiagPot.java
> +
Content missing?

2023-01-15 23:01 UTC, armadilloz commented on utils/ColorSensor.java
> +/*----------------------------------------------------------------------------*/
Duplicate file

2023-01-15 23:01 UTC, armadilloz commented on utils/MotorUtils.java
> +/*----------------------------------------------------------------------------*/
Duplicate file. This is the same for all the files under utils

2023-01-15 23:58 UTC, batchen1 commented on src/main/java/frc/robot/utils/diag/DiagPot.java
> +
added missing content

2023-01-16 00:00 UTC, batchen1 commented on utils/ColorSensor.java
> +/*----------------------------------------------------------------------------*/
removed

2023-01-16 00:00 UTC, batchen1 commented on utils/MotorUtils.java
> +/*----------------------------------------------------------------------------*/
removed

2023-01-17 00:21 UTC, armadilloz approved these changes

2023-01-21 16:04 UTC, merged