Auto Balence Options
FRC4048/FRC2023_Java pull request #52
Opened 2023-03-08 00:24 UTC by Sahiltheram

2023-03-08 13:05 UTC, batchen1 requested changes

2023-03-08 13:05 UTC, batchen1 commented on networktables.json
> +[]
delete this file.
When you add+commit+push, don't just do it automatically and add everything you changed. You have to look and select the files that you changed, then look at what you changed to confirm it is good and only then you add and commit them. These files are related to simulation and we don't want them in our branch.

2023-03-08 13:05 UTC, batchen1 commented on simgui-ds.json
> +{
same

2023-03-08 13:05 UTC, batchen1 commented on simgui.json
> +{
same

2023-03-08 13:05 UTC, batchen1 commented on src/main/java/frc/robot/AutonomousChooser.java
> +                x = 72;
we are always setting x to 72, why not just put it outside the if?

2023-03-08 13:05 UTC, batchen1 commented on src/main/java/frc/robot/AutonomousChooser.java
> +        else if (alliance == Alliance.Red) {
for red, we just need to add 99 to each option, no need to duplicate all the logic.

2023-03-08 13:05 UTC, batchen1 commented on src/main/java/frc/robot/AutonomousChooser.java
> +        else if (action == Action.DepositOneAndBalanceRight) {
now that we set odometry in the autonomous choose, our autonomous commands no longer need the alliance color as a parameter. Can you refactor and delete it?

2023-03-08 13:05 UTC, batchen1 commented on src/main/java/frc/robot/commands/Autonomous/Balance.java
> +            new MoveDistanceSpinTraj(drivetrain, 0, 3, Math.toRadians(180)),
I don't think we need to trajectory here, we assume drive team positioned the robot in the middle of the platform and that we can just start the balance command.

2023-03-08 13:05 UTC, batchen1 commented on src/main/java/frc/robot/commands/Autonomous/DepositOneAndBalance.java
> +            new MoveDistanceSpinTraj(drivetrain, 0.2 * direction, 1, Math.toRadians(180)),
we want to move 10cm forward (+x) and 20 cm on the y depending on direction (positive for moving right and negative for moving left), so the MoveDistanceSpinTraj should get 0.1 for the x and 0.2*direction for y.

2023-03-09 00:01 UTC, batchen1 approved these changes

2023-03-10 02:44 UTC, bengold22 approved these changes

2023-03-10 02:44 UTC, merged