Created logging branch
FRC4048/FRC2023_Java pull request #6
Opened 2023-01-29 18:29 UTC by SethCush

2023-01-31 01:51 UTC, MatthewSpofford requested changes
Take some time to think about recording joystick information. This could be useful down the road where we might be trying to debug an issue during practice/match and we want to know what button was pressed at that time. Take a look at the [WPILib docs on joystick logging](https://docs.wpilib.org/en/stable/docs/software/telemetry/datalog.html#logging-joystick-data).

2023-01-31 01:51 UTC, MatthewSpofford commented on src/main/java/frc/robot/Robot.java
> +    myStringLog = new StringLogEntry(log, "/my/string_log_example");
```suggestion
```
You can remove these example log entries. These entries won't be used anywhere else later on, so they aren't necessary anymore.

2023-01-31 01:51 UTC, MatthewSpofford commented on src/main/java/frc/robot/Robot.java
> +    myBoolLog.append(m_robotContainer.m_exampleSubsystem.exampleCondition());
You can remove this as well:
```suggestion
```

2023-01-31 01:51 UTC, MatthewSpofford commented on src/main/java/frc/robot/Robot.java
> +   BooleanLogEntry myBoolLog;
Remove this as well:
```suggestion
```

2023-01-31 01:51 UTC, MatthewSpofford commented on src/main/java/frc/robot/Robot.java
> +   DoubleLogEntry L2Log;
It might be a good idea to move these log entries to the `PowerDistPanel` class, and then add to the entries in the subsystems `periodic()` instead. That way, we aren't filling up `robotPeriodic()` with logging calls, and we also keep PDP related functionality in once place.

2023-01-31 01:51 UTC, MatthewSpofford commented on src/main/java/frc/robot/Robot.java
> +   DoubleLogEntry L2Log;
```suggestion
   private DoubleLogEntry R1Log;
   private DoubleLogEntry R2Log;
   private DoubleLogEntry L1Log;
   private DoubleLogEntry L2Log;
```

2023-01-31 01:51 UTC, MatthewSpofford commented on src/main/java/frc/robot/utils/MotorUtils.java
> +                DataLogManager.log("Motor stall, PDP channel =" + PDPChannel);
It might be useul to have an `IntegerLogEntry` in this class for logging which PDP channels are stalling. This way, we can keep the log a little more organized.

2023-03-18 19:21 UTC, bengold22 commented
I'm going to close this branch, we took Seth's work on enabling logging for CommandGroups and that is merged into WPIstaging now.

2023-03-18 19:21 UTC, closed without merging