Tof sensor
FRC4048/FRC2023_Java pull request #89
Opened 2023-03-21 01:47 UTC by fwc4838

New pickup commands.

TODO:
-Test gripper some more to make sure I didn't break it
-Change slow mode to a constant speed instead of a ratio of joystick input; tune this speed for pickup

2023-03-21 12:51 UTC, batchen1 requested changes

2023-03-21 12:51 UTC, batchen1 commented on src/main/java/frc/robot/commands/sequences/SubstationAutoPickup.java
> +            new VoltageMoveArm(arm, Constants.ARM_AUTO_VOLTAGE_UP, Constants.ARM_AUTO_VOLTAGE_DOWN, Constants.SUBSTATION_PICKUP_ANGLE),
Add wrappers around all sequences in SubstationAutoPickup, and also make sure each sequence has a name (name can be set in the instantiation or using setName()). Look at  OneGamePiece and  its binding as an example.

2023-03-21 12:51 UTC, batchen1 commented on src/main/java/frc/robot/commands/AutoCloseGripper.java
> +  public void end(boolean interrupted) {
Would be nice to log the AutoCloseGripper command, look at VoltageMoveArm as an example (need to extend a different class and call super in initialize and end).

2023-03-21 12:51 UTC, batchen1 commented on src/main/java/frc/robot/commands/sequences/SubstationAutoPickup.java
> +                        new ExtendToPosition(extender, 2000),
change to SUBSTATION_PICKUP_EXTENSION

2023-03-21 12:53 UTC, batchen1 commented on src/main/java/frc/robot/subsystems/Arm.java
>      return distanceSensor.getRange();
can we log the distance?

2023-03-21 13:40 UTC, armadilloz commented on src/main/java/frc/robot/commands/AutoCloseGripper.java
> -      new CloseGripper(gripper).schedule();
THe point of this was that the griper does not close in case of timeout. If the command moves this to a sequence, the gripper will close even if the TOF sensor did not sense the piece

2023-03-24 23:33 UTC, batchen1 approved these changes

2023-03-24 23:41 UTC, merged